// ========================================================
//  DSO TRACKER — Unified, Normalized, Catalog‑Grouped Database
//  Generated for Damien — ES Module Version
// ========================================================

export const DSO_DATABASE = [

  // --------------------------------------------------------
  // --- ALIGNMENT ------------------------------------------
  // --------------------------------------------------------
  {
    id: "NCP",
    name: "North Celestial Pole",
    ra: 0,
    dec: 90,
    type: "Alignment",
    subType: "Pole",
    dist: "N/A",
    season: ["All Year"],
    desc: "The exact True North rotational axis of the Earth.",
    catalog: "Alignment",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "SCP",
    name: "South Celestial Pole",
    ra: 0,
    dec: -90,
    type: "Alignment",
    subType: "Pole",
    dist: "N/A",
    season: ["All Year"],
    desc: "The exact True South rotational axis of the Earth.",
    catalog: "Alignment",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- STARS ----------------------------------------------
  // --------------------------------------------------------
  {
    id: "Acrux",
    name: "Southern Cross",
    ra: 186.6,
    dec: -63.1,
    type: "Star",
    subType: "Multiple",
    dist: "320 ly",
    season: ["Autumn"],
    desc: "The brightest star in the iconic Crux constellation.",
    catalog: "Star",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- CLOUDS ---------------------------------------------
  // --------------------------------------------------------
  {
    id: "Rho Oph",
    name: "Rho Ophiuchi Cloud",
    ra: 246.7,
    dec: -24.5,
    type: "Nebula",
    subType: "Molecular Cloud",
    dist: "460 ly",
    season: ["Winter"],
    desc: "A massive and incredibly colorful complex of dark, emission, and reflection nebulae.",
    catalog: "Cloud",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- DARK NEBULAE ---------------------------------------
  // --------------------------------------------------------
  {
    id: "C 99",
    name: "Coalsack Nebula",
    ra: 193.0,
    dec: -62.4,
    type: "Nebula",
    subType: "Dark",
    dist: "600 ly",
    season: ["Autumn"],
    desc: "A massive dark nebula right next to the Southern Cross.",
    catalog: "Dark Nebula",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- MAGELLANIC CLOUDS ----------------------------------
  // --------------------------------------------------------
  {
    id: "LMC",
    name: "Large Magellanic Cloud",
    ra: 80.9,
    dec: -69.75,
    type: "Galaxy",
    subType: "Dwarf Irregular",
    dist: "163,000 ly",
    season: ["Summer"],
    desc: "A satellite dwarf galaxy of the Milky Way.",
    catalog: "Magellanic",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "SMC",
    name: "Small Magellanic Cloud",
    ra: 13.2,
    dec: -72.8,
    type: "Galaxy",
    subType: "Dwarf Irregular",
    dist: "200,000 ly",
    season: ["Spring"],
    desc: "The smaller sibling to the LMC.",
    catalog: "Magellanic",
    alt: null,
    az: null,
    score: null
  },
  
  // --------------------------------------------------------
  // --- BARNARD (Dark Nebulae) -----------------------------
  // --------------------------------------------------------
  {
    id: "Barnard 33",
    name: "Horsehead Nebula",
    ra: 85.24,
    dec: -2.46,
    type: "Nebula",
    subType: "Dark",
    dist: "1,375 ly",
    season: ["Summer"],
    desc: "An iconic dark nebula silhouetted against the glowing IC 434 emission region.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 72",
    name: "Snake Nebula",
    ra: 260.95,
    dec: -23.63,
    type: "Nebula",
    subType: "Dark",
    dist: "650 ly",
    season: ["Winter"],
    desc: "A distinct, S-shaped dark dust lane slithering across the Milky Way star fields.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 86",
    name: "Ink Spot Nebula",
    ra: 270.78,
    dec: -29.83,
    type: "Nebula",
    subType: "Dark",
    dist: "6,000 ly",
    season: ["Winter"],
    desc: "A visually striking, pitch-black dark nebula blocking light from the stars behind it.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 92",
    name: "Dark Nebula",
    ra: 273.85,
    dec: -18.25,
    type: "Nebula",
    subType: "Dark",
    dist: "10,000 ly",
    season: ["Winter"],
    desc: "A prominent dark void silhouetted against the bright star cloud M24.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 93",
    name: "Dark Nebula",
    ra: 274.15,
    dec: -18.05,
    type: "Nebula",
    subType: "Dark",
    dist: "10,000 ly",
    season: ["Winter"],
    desc: "The companion dark dust cloud situated right next to Barnard 92 in M24.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 228",
    name: "Dark Nebula",
    ra: 236.80,
    dec: -34.50,
    type: "Nebula",
    subType: "Dark",
    dist: "500 ly",
    season: ["Winter"],
    desc: "A sprawling dark dust complex in the constellation Lupus.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 259",
    name: "Dark Nebula",
    ra: 258.50,
    dec: -26.10,
    type: "Nebula",
    subType: "Dark",
    dist: "600 ly",
    season: ["Winter"],
    desc: "A thick region of obscuring dust in Ophiuchus.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 268",
    name: "Dark Nebula",
    ra: 261.20,
    dec: -28.50,
    type: "Nebula",
    subType: "Dark",
    dist: "600 ly",
    season: ["Winter"],
    desc: "A dark molecular cloud blocking background starlight.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 270",
    name: "Dark Nebula",
    ra: 262.10,
    dec: -29.10,
    type: "Nebula",
    subType: "Dark",
    dist: "600 ly",
    season: ["Winter"],
    desc: "A shadowy void in the Milky Way band.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 283",
    name: "Dark Nebula",
    ra: 265.50,
    dec: -31.50,
    type: "Nebula",
    subType: "Dark",
    dist: "700 ly",
    season: ["Winter"],
    desc: "Dense dust obstructing the galactic core.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 288",
    name: "Dark Nebula",
    ra: 267.10,
    dec: -32.80,
    type: "Nebula",
    subType: "Dark",
    dist: "750 ly",
    season: ["Winter"],
    desc: "A dark nebula in the rich star fields of Scorpius.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 296",
    name: "Dark Nebula",
    ra: 271.50,
    dec: -34.20,
    type: "Nebula",
    subType: "Dark",
    dist: "800 ly",
    season: ["Winter"],
    desc: "A prominent dark lane in Sagittarius.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 312",
    name: "Dark Nebula",
    ra: 278.50,
    dec: -36.10,
    type: "Nebula",
    subType: "Dark",
    dist: "900 ly",
    season: ["Spring"],
    desc: "Thick dust obscuring southern star clusters.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 315",
    name: "Dark Nebula",
    ra: 282.10,
    dec: -37.50,
    type: "Nebula",
    subType: "Dark",
    dist: "950 ly",
    season: ["Spring"],
    desc: "A dark patch in the southern Milky Way.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 320",
    name: "Dark Nebula",
    ra: 285.50,
    dec: -38.20,
    type: "Nebula",
    subType: "Dark",
    dist: "1,000 ly",
    season: ["Spring"],
    desc: "A shadowy molecular cloud.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 327",
    name: "Dark Nebula",
    ra: 290.10,
    dec: -39.50,
    type: "Nebula",
    subType: "Dark",
    dist: "1,100 ly",
    season: ["Spring"],
    desc: "Deep sky dust lane.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 330",
    name: "Dark Nebula",
    ra: 293.50,
    dec: -40.10,
    type: "Nebula",
    subType: "Dark",
    dist: "1,200 ly",
    season: ["Spring"],
    desc: "An obscuring cloud in Corona Australis.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 335",
    name: "Dark Nebula",
    ra: 298.20,
    dec: 7.50,
    type: "Nebula",
    subType: "Dark",
    dist: "800 ly",
    season: ["Spring"],
    desc: "A well-known isolated Bok globule.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 337",
    name: "Dark Nebula",
    ra: 299.50,
    dec: -41.50,
    type: "Nebula",
    subType: "Dark",
    dist: "1,300 ly",
    season: ["Spring"],
    desc: "A southern dark cloud.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 340",
    name: "Dark Nebula",
    ra: 302.10,
    dec: -42.20,
    type: "Nebula",
    subType: "Dark",
    dist: "1,400 ly",
    season: ["Spring"],
    desc: "A dense dark nebula.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 341",
    name: "Dark Nebula",
    ra: 303.50,
    dec: -43.10,
    type: "Nebula",
    subType: "Dark",
    dist: "1,500 ly",
    season: ["Spring"],
    desc: "Dust blocking the Milky Way.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 343",
    name: "Dark Nebula",
    ra: 305.20,
    dec: 40.80,
    type: "Nebula",
    subType: "Dark",
    dist: "1,000 ly",
    season: ["Spring"],
    desc: "A dark nebula in Cygnus.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 344",
    name: "Dark Nebula",
    ra: 306.80,
    dec: -44.50,
    type: "Nebula",
    subType: "Dark",
    dist: "1,600 ly",
    season: ["Spring"],
    desc: "A southern dark lane.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 345",
    name: "Dark Nebula",
    ra: 308.10,
    dec: -45.20,
    type: "Nebula",
    subType: "Dark",
    dist: "1,700 ly",
    season: ["Spring"],
    desc: "Obscuring dust in the southern skies.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 346",
    name: "Dark Nebula",
    ra: 309.50,
    dec: -46.10,
    type: "Nebula",
    subType: "Dark",
    dist: "1,800 ly",
    season: ["Spring"],
    desc: "A dark cloud blocking distant starlight.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 347",
    name: "Dark Nebula",
    ra: 311.20,
    dec: -47.50,
    type: "Nebula",
    subType: "Dark",
    dist: "1,900 ly",
    season: ["Spring"],
    desc: "A dense patch of the southern Milky Way.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 348",
    name: "Dark Nebula",
    ra: 315.50,
    dec: 42.50,
    type: "Nebula",
    subType: "Dark",
    dist: "1,200 ly",
    season: ["Spring"],
    desc: "A dark region in the northern cross.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 349",
    name: "Dark Nebula",
    ra: 317.10,
    dec: -48.20,
    type: "Nebula",
    subType: "Dark",
    dist: "2,000 ly",
    season: ["Spring"],
    desc: "A deep southern dark nebula.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Barnard 350",
    name: "Dark Nebula",
    ra: 319.50,
    dec: -49.50,
    type: "Nebula",
    subType: "Dark",
    dist: "2,100 ly",
    season: ["Spring"],
    desc: "A prominent dark cloud in the southern hemisphere.",
    catalog: "Barnard",
    alt: null,
    az: null,
    score: null
  },
  
  // --------------------------------------------------------
  // --- COLLINDER (Open Clusters) --------------------------
  // --------------------------------------------------------
  {
    id: "Collinder 140",
    name: "Open Cluster",
    ra: 111.00,
    dec: -31.85,
    type: "Cluster",
    subType: "Open",
    dist: "1,200 ly",
    season: ["Summer"],
    desc: "A large, bright open cluster easily visible in binoculars.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 173",
    name: "Open Cluster",
    ra: 124.00,
    dec: -46.30,
    type: "Cluster",
    subType: "Open",
    dist: "1,500 ly",
    season: ["Summer"],
    desc: "A sparse grouping of stars.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 197",
    name: "Open Cluster",
    ra: 133.50,
    dec: -49.10,
    type: "Cluster",
    subType: "Open",
    dist: "2,000 ly",
    season: ["Autumn"],
    desc: "A minor open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 220",
    name: "Open Cluster",
    ra: 145.20,
    dec: -52.40,
    type: "Cluster",
    subType: "Open",
    dist: "2,500 ly",
    season: ["Autumn"],
    desc: "An open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 223",
    name: "Open Cluster",
    ra: 148.50,
    dec: -54.10,
    type: "Cluster",
    subType: "Open",
    dist: "2,800 ly",
    season: ["Autumn"],
    desc: "A southern cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 228",
    name: "Open Cluster",
    ra: 156.00,
    dec: -60.00,
    type: "Cluster",
    subType: "Open",
    dist: "7,000 ly",
    season: ["Autumn"],
    desc: "A large open cluster associated with the Carina Nebula.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 232",
    name: "Open Cluster",
    ra: 158.50,
    dec: -61.50,
    type: "Cluster",
    subType: "Open",
    dist: "6,500 ly",
    season: ["Autumn"],
    desc: "A massive open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 238",
    name: "Open Cluster",
    ra: 162.20,
    dec: -63.10,
    type: "Cluster",
    subType: "Open",
    dist: "3,000 ly",
    season: ["Autumn"],
    desc: "A deep sky cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 258",
    name: "Open Cluster",
    ra: 170.50,
    dec: -65.20,
    type: "Cluster",
    subType: "Open",
    dist: "4,000 ly",
    season: ["Autumn"],
    desc: "An obscure Collinder entry.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 272",
    name: "Open Cluster",
    ra: 185.10,
    dec: -60.50,
    type: "Cluster",
    subType: "Open",
    dist: "3,500 ly",
    season: ["Autumn"],
    desc: "A faint southern cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 282",
    name: "Open Cluster",
    ra: 195.50,
    dec: -62.10,
    type: "Cluster",
    subType: "Open",
    dist: "4,200 ly",
    season: ["Winter"],
    desc: "An open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 285",
    name: "Ursa Major Cluster",
    ra: 189.50,
    dec: 55.50,
    type: "Cluster",
    subType: "Open",
    dist: "80 ly",
    season: ["Winter"],
    desc: "The closest open cluster to Earth, forming the core of the Big Dipper.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 292",
    name: "Open Cluster",
    ra: 205.10,
    dec: -63.50,
    type: "Cluster",
    subType: "Open",
    dist: "3,000 ly",
    season: ["Winter"],
    desc: "A faint southern open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 296",
    name: "Open Cluster",
    ra: 215.50,
    dec: -64.10,
    type: "Cluster",
    subType: "Open",
    dist: "3,200 ly",
    season: ["Winter"],
    desc: "A grouping of stars.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 299",
    name: "Open Cluster",
    ra: 225.10,
    dec: -65.50,
    type: "Cluster",
    subType: "Open",
    dist: "3,500 ly",
    season: ["Winter"],
    desc: "A minor cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 302",
    name: "Open Cluster",
    ra: 235.50,
    dec: -66.10,
    type: "Cluster",
    subType: "Open",
    dist: "3,800 ly",
    season: ["Winter"],
    desc: "A deep sky object.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 305",
    name: "Open Cluster",
    ra: 245.10,
    dec: -67.50,
    type: "Cluster",
    subType: "Open",
    dist: "4,000 ly",
    season: ["Winter"],
    desc: "A faint southern target.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 307",
    name: "Open Cluster",
    ra: 255.50,
    dec: -68.10,
    type: "Cluster",
    subType: "Open",
    dist: "4,200 ly",
    season: ["Winter"],
    desc: "A sparse open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 316",
    name: "Open Cluster",
    ra: 265.10,
    dec: -69.50,
    type: "Cluster",
    subType: "Open",
    dist: "4,500 ly",
    season: ["Winter"],
    desc: "A deep sky cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 320",
    name: "Open Cluster",
    ra: 275.50,
    dec: -70.10,
    type: "Cluster",
    subType: "Open",
    dist: "4,800 ly",
    season: ["Winter"],
    desc: "An open cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 323",
    name: "Open Cluster",
    ra: 285.10,
    dec: -71.50,
    type: "Cluster",
    subType: "Open",
    dist: "5,000 ly",
    season: ["Spring"],
    desc: "A faint grouping of stars.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 328",
    name: "Open Cluster",
    ra: 295.50,
    dec: -72.10,
    type: "Cluster",
    subType: "Open",
    dist: "5,200 ly",
    season: ["Spring"],
    desc: "A southern cluster.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Collinder 335",
    name: "Open Cluster",
    ra: 305.10,
    dec: -73.50,
    type: "Cluster",
    subType: "Open",
    dist: "5,500 ly",
    season: ["Spring"],
    desc: "The final Collinder cluster in this batch.",
    catalog: "Collinder",
    alt: null,
    az: null,
    score: null
  },
  
  // --------------------------------------------------------
  // --- IC (Index Catalogue) -------------------------------
  // --------------------------------------------------------
  {
    id: "IC 2177",
    name: "Seagull Nebula",
    ra: 106.12,
    dec: -10.64,
    type: "Nebula",
    subType: "Emission",
    dist: "3,650 ly",
    season: ["Summer"],
    desc: "A large region of nebulosity marking the head and wings of the Seagull.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2220",
    name: "Toby Jug Nebula",
    ra: 119.12,
    dec: -59.13,
    type: "Nebula",
    subType: "Reflection",
    dist: "1,200 ly",
    season: ["Summer"],
    desc: "A distinctive reflection nebula surrounding a red giant star.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2391",
    name: "Omicron Velorum Cluster",
    ra: 130.13,
    dec: -53.03,
    type: "Cluster",
    subType: "Open",
    dist: "500 ly",
    season: ["Summer"],
    desc: "A very bright, close open cluster centered on the star Omicron Velorum.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2395",
    name: "Open Cluster",
    ra: 130.70,
    dec: -48.11,
    type: "Cluster",
    subType: "Open",
    dist: "2,500 ly",
    season: ["Summer"],
    desc: "A scattered open cluster in Vela.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2488",
    name: "Open Cluster",
    ra: 141.88,
    dec: -56.96,
    type: "Cluster",
    subType: "Open",
    dist: "4,000 ly",
    season: ["Autumn"],
    desc: "A faint, rich open cluster.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2581",
    name: "Open Cluster",
    ra: 156.88,
    dec: -57.62,
    type: "Cluster",
    subType: "Open",
    dist: "9,000 ly",
    season: ["Autumn"],
    desc: "An open cluster heavily obscured by background dust.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2602",
    name: "Southern Pleiades",
    ra: 160.7,
    dec: -64.4,
    type: "Cluster",
    subType: "Open",
    dist: "479 ly",
    season: ["Autumn"],
    desc: "A large, bright open cluster in Carina.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2604",
    name: "Galaxy",
    ra: 160.75,
    dec: -64.45,
    type: "Galaxy",
    subType: "Spiral",
    dist: "65 Million ly",
    season: ["Autumn"],
    desc: "A faint, diffuse spiral galaxy near the Southern Pleiades.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 2606",
    name: "Open Cluster",
    ra: 161.20,
    dec: -58.80,
    type: "Cluster",
    subType: "Open",
    dist: "1,500 ly",
    season: ["Autumn"],
    desc: "A sparse open cluster.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  
  {
    id: "IC 2944",
    name: "Running Chicken Nebula",
    ra: 174.0,
    dec: -63.0,
    type: "Nebula",
    subType: "Emission",
    dist: "6,500 ly",
    season: ["Autumn"],
    desc: "An emission nebula with distinct dark Bok globules.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 410",
    name: "Tadpoles Nebula",
    ra: 79.10,
    dec: 33.40,
    type: "Nebula",
    subType: "Emission",
    dist: "12,000 ly",
    season: ["Summer"],
    desc: "An emission nebula harboring massive dust pillars shaped like tadpoles.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 418",
    name: "Spirograph Nebula",
    ra: 81.82,
    dec: -12.69,
    type: "Nebula",
    subType: "Planetary",
    dist: "3,600 ly",
    season: ["Summer"],
    desc: "A young planetary nebula with intricate, geometric textural patterns.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4406",
    name: "Retina Nebula",
    ra: 243.60,
    dec: -44.38,
    type: "Nebula",
    subType: "Planetary",
    dist: "2,000 ly",
    season: ["Winter"],
    desc: "A cylindrical planetary nebula viewed from the side.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4592",
    name: "Blue Horsehead",
    ra: 242.98,
    dec: -19.46,
    type: "Nebula",
    subType: "Reflection",
    dist: "400 ly",
    season: ["Winter"],
    desc: "A large reflection nebula illuminated by Nu Scorpii.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4634",
    name: "Nebula",
    ra: 255.40,
    dec: -21.83,
    type: "Nebula",
    subType: "Planetary",
    dist: "7,500 ly",
    season: ["Winter"],
    desc: "A small planetary nebula showing S-shaped point-symmetric structure.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4637",
    name: "Nebula",
    ra: 256.40,
    dec: -40.80,
    type: "Nebula",
    subType: "Emission",
    dist: "8,000 ly",
    season: ["Winter"],
    desc: "A compact deep sky nebula.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4678",
    name: "Nebula",
    ra: 262.15,
    dec: -23.95,
    type: "Nebula",
    subType: "Emission",
    dist: "5,000 ly",
    season: ["Winter"],
    desc: "An emission nebula near the Trifid Nebula complex.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4685",
    name: "Lagoon Extension",
    ra: 272.25,
    dec: -23.98,
    type: "Nebula",
    subType: "Emission",
    dist: "4,100 ly",
    season: ["Winter"],
    desc: "A bright patch of nebulosity associated with the Lagoon Nebula.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4701",
    name: "Nebula",
    ra: 275.28,
    dec: -16.65,
    type: "Nebula",
    subType: "Emission",
    dist: "5,500 ly",
    season: ["Winter"],
    desc: "Part of the greater Omega Nebula star-forming region.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "IC 4776",
    name: "Planetary Nebula",
    ra: 281.38,
    dec: -33.34,
    type: "Nebula",
    subType: "Planetary",
    dist: "10,000 ly",
    season: ["Spring"],
    desc: "A planetary nebula with a distinct, elongated morphology.",
    catalog: "IC",
    alt: null,
    az: null,
    score: null
  },
  
  // --------------------------------------------------------
  // --- MELOTTE (Open Clusters) ----------------------------
  // --------------------------------------------------------
  {
    id: "Melotte 66",
    name: "Open Cluster",
    ra: 111.55,
    dec: -47.66,
    type: "Cluster",
    subType: "Open",
    dist: "15,000 ly",
    season: ["Summer"],
    desc: "An incredibly old, distant open cluster.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 71",
    name: "Open Cluster",
    ra: 114.39,
    dec: -12.06,
    type: "Cluster",
    subType: "Open",
    dist: "10,000 ly",
    season: ["Summer"],
    desc: "A rich open cluster.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 72",
    name: "Open Cluster",
    ra: 114.61,
    dec: -10.66,
    type: "Cluster",
    subType: "Open",
    dist: "9,500 ly",
    season: ["Summer"],
    desc: "A distant open cluster.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 77",
    name: "Open Cluster",
    ra: 115.10,
    dec: -10.10,
    type: "Cluster",
    subType: "Open",
    dist: "8,000 ly",
    season: ["Summer"],
    desc: "An obscure southern cluster.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 101",
    name: "Open Cluster",
    ra: 160.60,
    dec: -65.10,
    type: "Cluster",
    subType: "Open",
    dist: "5,500 ly",
    season: ["Autumn"],
    desc: "An open cluster in the Carina region.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 102",
    name: "Open Cluster",
    ra: 162.10,
    dec: -64.40,
    type: "Cluster",
    subType: "Open",
    dist: "5,000 ly",
    season: ["Autumn"],
    desc: "A nearby open cluster.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 103",
    name: "Open Cluster",
    ra: 163.50,
    dec: -64.10,
    type: "Cluster",
    subType: "Open",
    dist: "4,500 ly",
    season: ["Autumn"],
    desc: "A star cluster in the southern sky.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Melotte 104",
    name: "Open Cluster",
    ra: 164.20,
    dec: -63.80,
    type: "Cluster",
    subType: "Open",
    dist: "4,000 ly",
    season: ["Autumn"],
    desc: "A faint open cluster.",
    catalog: "Melotte",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- MESSIER (Clusters, Nebulae, Galaxies) --------------
  // --------------------------------------------------------
  {
    id: "M 8",
    name: "Lagoon Nebula",
    ra: 270.9,
    dec: -24.3,
    type: "Nebula",
    subType: "Emission",
    dist: "4,100 ly",
    season: ["Winter"],
    desc: "A giant interstellar cloud in Sagittarius.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 16",
    name: "Eagle Nebula",
    ra: 274.7,
    dec: -13.8,
    type: "Nebula",
    subType: "Emission",
    dist: "7,000 ly",
    season: ["Winter"],
    desc: "Famous for the 'Pillars of Creation'.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 17",
    name: "Omega Nebula",
    ra: 275.2,
    dec: -16.2,
    type: "Nebula",
    subType: "Emission",
    dist: "5,500 ly",
    season: ["Winter"],
    desc: "Also known as the Swan Nebula.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 20",
    name: "Trifid Nebula",
    ra: 270.6,
    dec: -23.0,
    type: "Nebula",
    subType: "Mixed",
    dist: "5,200 ly",
    season: ["Winter"],
    desc: "A rare combination of emission, reflection, and dark nebula.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 31",
    name: "Andromeda Galaxy",
    ra: 10.684,
    dec: 41.269,
    type: "Galaxy",
    subType: "Spiral",
    dist: "2.5 Million ly",
    season: ["Spring"],
    desc: "The closest major galaxy to the Milky Way.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 41",
    name: "Little Beehive Cluster",
    ra: 101.5,
    dec: -20.7,
    type: "Cluster",
    subType: "Open",
    dist: "2,300 ly",
    season: ["Summer"],
    desc: "Located just below Sirius in Canis Major.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 42",
    name: "Orion Nebula",
    ra: 83.822,
    dec: -5.391,
    type: "Nebula",
    subType: "Emission",
    dist: "1,344 ly",
    season: ["Summer"],
    desc: "The brightest and most famous star-forming region in the sky.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 93",
    name: "Messier 93",
    ra: 116.1,
    dec: -23.85,
    type: "Cluster",
    subType: "Open",
    dist: "3,600 ly",
    season: ["Winter"],
    desc: "A dense, bright open cluster in Puppis.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "M 104",
    name: "Sombrero Galaxy",
    ra: 189.9,
    dec: -11.6,
    type: "Galaxy",
    subType: "Spiral",
    dist: "31.1 Million ly",
    season: ["Autumn"],
    desc: "A spiral galaxy with a brilliant core and thick dust lane.",
    catalog: "Messier",
    alt: null,
    az: null,
    score: null
  },
  
  // --------------------------------------------------------
  // --- NGC (New General Catalogue) ------------------------
  // --------------------------------------------------------
  {
    id: "NGC 45",
    name: "Spiral Galaxy",
    ra: 3.51,
    dec: -23.18,
    type: "Galaxy",
    subType: "Spiral",
    dist: "22 Million ly",
    season: ["Spring"],
    desc: "A low surface brightness spiral galaxy in the constellation Cetus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 55",
    name: "Sculptor Group Galaxy",
    ra: 3.75,
    dec: -39.19,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "6.5 Million ly",
    season: ["Spring"],
    desc: "A prominent edge-on barred spiral galaxy in the Sculptor group.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 104",
    name: "47 Tucanae",
    ra: 6.0,
    dec: -72.08,
    type: "Cluster",
    subType: "Globular",
    dist: "13,000 ly",
    season: ["Spring"],
    desc: "The second brightest globular cluster in the sky.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1316",
    name: "Fornax A",
    ra: 50.67,
    dec: -37.20,
    type: "Galaxy",
    subType: "Lenticular",
    dist: "60 Million ly",
    season: ["Summer"],
    desc: "A giant lenticular galaxy and an incredibly strong radio source.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 134",
    name: "Spiral Galaxy",
    ra: 7.57,
    dec: -33.25,
    type: "Galaxy",
    subType: "Spiral",
    dist: "60 Million ly",
    season: ["Spring"],
    desc: "A tilted spiral galaxy resembling a smaller version of the Milky Way.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1399",
    name: "Fornax Cluster Core",
    ra: 54.62,
    dec: -35.45,
    type: "Galaxy",
    subType: "Elliptical",
    dist: "65 Million ly",
    season: ["Summer"],
    desc: "The central, massive elliptical galaxy of the Fornax Cluster.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1404",
    name: "Elliptical Galaxy",
    ra: 54.73,
    dec: -35.59,
    type: "Galaxy",
    subType: "Elliptical",
    dist: "65 Million ly",
    season: ["Summer"],
    desc: "A bright elliptical galaxy falling towards the center of the Fornax cluster.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1427A",
    name: "Irregular Galaxy",
    ra: 55.05,
    dec: -35.62,
    type: "Galaxy",
    subType: "Irregular",
    dist: "52 Million ly",
    season: ["Summer"],
    desc: "An irregular galaxy being distorted by its plunge into the Fornax cluster.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1433",
    name: "Ringed Galaxy",
    ra: 55.51,
    dec: -47.22,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "30 Million ly",
    season: ["Summer"],
    desc: "A beautiful barred spiral featuring a prominent double ring structure.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1487",
    name: "Interacting Galaxy",
    ra: 58.91,
    dec: -42.37,
    type: "Galaxy",
    subType: "Interacting",
    dist: "30 Million ly",
    season: ["Summer"],
    desc: "Actually a merging system of two or three dwarf galaxies.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1512",
    name: "Barred Spiral Galaxy",
    ra: 60.98,
    dec: -43.35,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "38 Million ly",
    season: ["Summer"],
    desc: "Features an intricate circumnuclear starburst ring.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1553",
    name: "Lenticular Galaxy",
    ra: 64.04,
    dec: -55.78,
    type: "Galaxy",
    subType: "Lenticular",
    dist: "45 Million ly",
    season: ["Summer"],
    desc: "The second brightest member of the Dorado group of galaxies.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1566",
    name: "Spanish Dancer Galaxy",
    ra: 65.00,
    dec: -54.94,
    type: "Galaxy",
    subType: "Spiral",
    dist: "40 Million ly",
    season: ["Summer"],
    desc: "A striking, grand-design face-on spiral galaxy in the Dorado group.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1672",
    name: "Barred Spiral",
    ra: 71.43,
    dec: -59.25,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "60 Million ly",
    season: ["Summer"],
    desc: "A highly active barred spiral with intense star formation in its central bar.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1705",
    name: "Dwarf Galaxy",
    ra: 73.55,
    dec: -53.36,
    type: "Galaxy",
    subType: "Dwarf",
    dist: "17 Million ly",
    season: ["Summer"],
    desc: "A blue compact dwarf galaxy with a massive central star cluster.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1744",
    name: "Spiral Galaxy",
    ra: 74.99,
    dec: -26.02,
    type: "Galaxy",
    subType: "Spiral",
    dist: "30 Million ly",
    season: ["Summer"],
    desc: "A faint, unbarred spiral galaxy in the constellation Lepus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1792",
    name: "Spiral Galaxy",
    ra: 76.32,
    dec: -37.98,
    type: "Galaxy",
    subType: "Spiral",
    dist: "50 Million ly",
    season: ["Summer"],
    desc: "A starburst spiral galaxy, very luminous in infrared light.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 1808",
    name: "Starburst Galaxy",
    ra: 76.93,
    dec: -37.51,
    type: "Galaxy",
    subType: "Starburst",
    dist: "40 Million ly",
    season: ["Summer"],
    desc: "A Seyfert galaxy currently undergoing a massive wave of star formation.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 2070",
    name: "Tarantula Nebula",
    ra: 84.6,
    dec: -69.1,
    type: "Nebula",
    subType: "Emission",
    dist: "160,000 ly",
    season: ["Summer"],
    desc: "The most active starburst region known in the Local Group.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 2188",
    name: "Edge-on Galaxy",
    ra: 92.51,
    dec: -34.10,
    type: "Galaxy",
    subType: "Edge-on",
    dist: "25 Million ly",
    season: ["Summer"],
    desc: "A highly tilted barred spiral that looks like a thin sliver of light.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 2359",
    name: "Thor's Helmet",
    ra: 109.6,
    dec: -13.2,
    type: "Nebula",
    subType: "Emission",
    dist: "11,960 ly",
    season: ["Summer"],
    desc: "A complex bubble blown by a Wolf-Rayet star.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 2442",
    name: "Meathook Galaxy",
    ra: 114.07,
    dec: -69.53,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "50 Million ly",
    season: ["Autumn"],
    desc: "An asymmetric barred spiral with one elongated, hook-like arm.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 253",
    name: "Sculptor Galaxy",
    ra: 11.9,
    dec: -25.28,
    type: "Galaxy",
    subType: "Starburst",
    dist: "11.4 Million ly",
    season: ["Spring"],
    desc: "A spectacular starburst galaxy.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  
  {
    id: "NGC 2835",
    name: "Spiral Galaxy",
    ra: 139.47,
    dec: -22.35,
    type: "Galaxy",
    subType: "Spiral",
    dist: "35 Million ly",
    season: ["Autumn"],
    desc: "A face-on spiral galaxy with well‑defined arms.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 292",
    name: "Small Magellanic Cloud Core",
    ra: 13.2,
    dec: -72.8,
    type: "Galaxy",
    subType: "Dwarf Irregular",
    dist: "200,000 ly",
    season: ["Spring"],
    desc: "The central region of the SMC, containing dense star fields.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 300",
    name: "Spiral Galaxy",
    ra: 13.72,
    dec: -37.68,
    type: "Galaxy",
    subType: "Spiral",
    dist: "6.5 Million ly",
    season: ["Spring"],
    desc: "A bright, nearby spiral galaxy in Sculptor.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3132",
    name: "Southern Ring Nebula",
    ra: 153.3,
    dec: -40.4,
    type: "Nebula",
    subType: "Planetary",
    dist: "2,000 ly",
    season: ["Autumn"],
    desc: "A bright planetary nebula famously imaged by JWST.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3201",
    name: "Globular Cluster",
    ra: 154.4,
    dec: -46.4,
    type: "Cluster",
    subType: "Globular",
    dist: "16,300 ly",
    season: ["Autumn"],
    desc: "A fast‑moving globular cluster with unusual kinematics.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3293",
    name: "Gem Cluster",
    ra: 158.96,
    dec: -58.23,
    type: "Cluster",
    subType: "Open",
    dist: "8,400 ly",
    season: ["Autumn"],
    desc: "A compact open cluster packed with brilliant blue and red supergiants.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3372",
    name: "Carina Nebula",
    ra: 161.26,
    dec: -59.68,
    type: "Nebula",
    subType: "Emission",
    dist: "8,500 ly",
    season: ["Autumn"],
    desc: "One of the largest and brightest nebulae in the sky, home to Eta Carinae.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 346",
    name: "SMC Star‑Forming Region",
    ra: 14.8,
    dec: -72.2,
    type: "Nebula",
    subType: "Emission",
    dist: "210,000 ly",
    season: ["Spring"],
    desc: "The brightest star‑forming region in the Small Magellanic Cloud.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3532",
    name: "Wishing Well Cluster",
    ra: 166.4,
    dec: -58.75,
    type: "Cluster",
    subType: "Open",
    dist: "1,300 ly",
    season: ["Autumn"],
    desc: "A rich open cluster that sparkles like coins in a fountain.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 362",
    name: "Globular Cluster",
    ra: 15.6,
    dec: -70.8,
    type: "Cluster",
    subType: "Globular",
    dist: "27,000 ly",
    season: ["Spring"],
    desc: "A bright globular cluster near the SMC.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3766",
    name: "Pearl Cluster",
    ra: 174.01,
    dec: -61.61,
    type: "Cluster",
    subType: "Open",
    dist: "5,500 ly",
    season: ["Autumn"],
    desc: "An exceptionally rich open cluster known for its many Be‑type stars.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3918",
    name: "Blue Planetary",
    ra: 177.53,
    dec: -57.18,
    type: "Nebula",
    subType: "Planetary",
    dist: "4,900 ly",
    season: ["Autumn"],
    desc: "A bright planetary nebula with a rich blue hue, resembling Neptune.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 3923",
    name: "Shell Galaxy",
    ra: 177.78,
    dec: -28.78,
    type: "Galaxy",
    subType: "Elliptical",
    dist: "90 Million ly",
    season: ["Autumn"],
    desc: "A massive elliptical galaxy surrounded by faint stellar shells.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  
  {
    id: "NGC 4103",
    name: "Open Cluster",
    ra: 181.13,
    dec: -61.25,
    type: "Cluster",
    subType: "Open",
    dist: "5,700 ly",
    season: ["Autumn"],
    desc: "A bright open cluster in Crux with dozens of hot blue stars.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4372",
    name: "Globular Cluster",
    ra: 186.44,
    dec: -72.66,
    type: "Cluster",
    subType: "Globular",
    dist: "18,900 ly",
    season: ["Autumn"],
    desc: "A loose, faint globular cluster in the southern sky.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4463",
    name: "Open Cluster",
    ra: 187.95,
    dec: -64.78,
    type: "Cluster",
    subType: "Open",
    dist: "3,300 ly",
    season: ["Autumn"],
    desc: "A compact open cluster located near the Running Chicken Nebula.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4609",
    name: "Open Cluster",
    ra: 190.98,
    dec: -62.99,
    type: "Cluster",
    subType: "Open",
    dist: "4,000 ly",
    season: ["Autumn"],
    desc: "A small open cluster near the Coalsack Nebula.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4755",
    name: "Jewel Box Cluster",
    ra: 193.29,
    dec: -60.37,
    type: "Cluster",
    subType: "Open",
    dist: "6,440 ly",
    season: ["Autumn"],
    desc: "One of the most colorful open clusters, containing bright red and blue supergiants.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4833",
    name: "Globular Cluster",
    ra: 194.89,
    dec: -70.88,
    type: "Cluster",
    subType: "Globular",
    dist: "21,200 ly",
    season: ["Autumn"],
    desc: "A large but loosely concentrated globular cluster in Musca.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4945",
    name: "Starburst Galaxy",
    ra: 196.36,
    dec: -49.47,
    type: "Galaxy",
    subType: "Starburst",
    dist: "13 Million ly",
    season: ["Autumn"],
    desc: "A massive edge‑on starburst galaxy, one of the brightest infrared galaxies in the sky.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 4976",
    name: "Elliptical Galaxy",
    ra: 197.04,
    dec: -49.50,
    type: "Galaxy",
    subType: "Elliptical",
    dist: "41 Million ly",
    season: ["Autumn"],
    desc: "A smooth elliptical galaxy located near the starburst galaxy NGC 4945.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5128",
    name: "Centaurus A",
    ra: 201.37,
    dec: -43.02,
    type: "Galaxy",
    subType: "Elliptical",
    dist: "12 Million ly",
    season: ["Autumn"],
    desc: "A peculiar galaxy with a dramatic dust lane and one of the strongest radio sources in the sky.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5139",
    name: "Omega Centauri",
    ra: 201.70,
    dec: -47.48,
    type: "Cluster",
    subType: "Globular",
    dist: "15,800 ly",
    season: ["Autumn"],
    desc: "The largest and brightest globular cluster in the Milky Way, possibly the core of a dwarf galaxy.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5189",
    name: "Spiral Planetary Nebula",
    ra: 203.55,
    dec: -65.98,
    type: "Nebula",
    subType: "Planetary",
    dist: "1,780 ly",
    season: ["Autumn"],
    desc: "A chaotic, S‑shaped planetary nebula with complex filamentary structure.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  
  {
    id: "NGC 5286",
    name: "Globular Cluster",
    ra: 206.61,
    dec: -51.37,
    type: "Cluster",
    subType: "Globular",
    dist: "35,000 ly",
    season: ["Autumn"],
    desc: "A bright, compact globular cluster in Centaurus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5291",
    name: "Interacting Galaxy System",
    ra: 206.91,
    dec: -30.25,
    type: "Galaxy",
    subType: "Interacting",
    dist: "200 Million ly",
    season: ["Autumn"],
    desc: "A dramatic collisional ring galaxy with long tidal debris trails.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5367",
    name: "Reflection Nebula",
    ra: 209.25,
    dec: -40.67,
    type: "Nebula",
    subType: "Reflection",
    dist: "2,000 ly",
    season: ["Autumn"],
    desc: "A dusty reflection nebula illuminated by a pair of young stars.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5460",
    name: "Open Cluster",
    ra: 211.53,
    dec: -48.34,
    type: "Cluster",
    subType: "Open",
    dist: "2,000 ly",
    season: ["Autumn"],
    desc: "A large, loose open cluster in Centaurus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5823",
    name: "Open Cluster",
    ra: 225.50,
    dec: -55.58,
    type: "Cluster",
    subType: "Open",
    dist: "3,500 ly",
    season: ["Winter"],
    desc: "A rich open cluster located in Circinus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5927",
    name: "Globular Cluster",
    ra: 232.00,
    dec: -50.67,
    type: "Cluster",
    subType: "Globular",
    dist: "25,000 ly",
    season: ["Winter"],
    desc: "A metal‑rich globular cluster near the Milky Way bulge.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 5986",
    name: "Globular Cluster",
    ra: 236.51,
    dec: -37.79,
    type: "Cluster",
    subType: "Globular",
    dist: "35,000 ly",
    season: ["Winter"],
    desc: "A bright globular cluster with a dense core.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6025",
    name: "Open Cluster",
    ra: 240.00,
    dec: -60.42,
    type: "Cluster",
    subType: "Open",
    dist: "2,700 ly",
    season: ["Winter"],
    desc: "A triangular open cluster in Triangulum Australe.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6087",
    name: "S Normae Cluster",
    ra: 244.75,
    dec: -57.94,
    type: "Cluster",
    subType: "Open",
    dist: "3,500 ly",
    season: ["Winter"],
    desc: "A bright open cluster containing the Cepheid variable S Normae.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6101",
    name: "Globular Cluster",
    ra: 246.45,
    dec: -72.20,
    type: "Cluster",
    subType: "Globular",
    dist: "47,600 ly",
    season: ["Winter"],
    desc: "A faint, loosely concentrated globular cluster in Apus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 613",
    name: "Barred Spiral Galaxy",
    ra: 24.15,
    dec: -29.25,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "67 Million ly",
    season: ["Spring"],
    desc: "A grand‑design barred spiral with strong star‑forming regions.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6164",
    name: "Emission Nebula",
    ra: 248.15,
    dec: -48.00,
    type: "Nebula",
    subType: "Emission",
    dist: "4,200 ly",
    season: ["Winter"],
    desc: "A bipolar nebula formed by a massive O‑type star shedding material.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6188",
    name: "Rim Nebula",
    ra: 249.00,
    dec: -48.00,
    type: "Nebula",
    subType: "Emission",
    dist: "4,000 ly",
    season: ["Winter"],
    desc: "A dramatic star‑forming region with sharp dust ridges.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6193",
    name: "Open Cluster",
    ra: 249.15,
    dec: -48.77,
    type: "Cluster",
    subType: "Open",
    dist: "3,800 ly",
    season: ["Winter"],
    desc: "A young open cluster powering the Rim Nebula (NGC 6188).",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6200",
    name: "Open Cluster",
    ra: 250.00,
    dec: -47.48,
    type: "Cluster",
    subType: "Open",
    dist: "3,500 ly",
    season: ["Winter"],
    desc: "A compact open cluster in Ara.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6231",
    name: "Northern Jewel Box",
    ra: 253.54,
    dec: -41.82,
    type: "Cluster",
    subType: "Open",
    dist: "5,200 ly",
    season: ["Winter"],
    desc: "A brilliant open cluster marking the head of the Scorpius OB association.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6242",
    name: "Open Cluster",
    ra: 254.30,
    dec: -39.47,
    type: "Cluster",
    subType: "Open",
    dist: "3,900 ly",
    season: ["Winter"],
    desc: "A moderately rich open cluster in Scorpius.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6254",
    name: "M10 Globular Cluster",
    ra: 254.29,
    dec: -4.10,
    type: "Cluster",
    subType: "Globular",
    dist: "14,300 ly",
    season: ["Winter"],
    desc: "A bright globular cluster in Ophiuchus.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6302",
    name: "Bug Nebula",
    ra: 258.43,
    dec: -37.10,
    type: "Nebula",
    subType: "Planetary",
    dist: "3,400 ly",
    season: ["Winter"],
    desc: "A bipolar planetary nebula with an extremely hot central star.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6352",
    name: "Globular Cluster",
    ra: 261.37,
    dec: -48.42,
    type: "Cluster",
    subType: "Globular",
    dist: "19,500 ly",
    season: ["Winter"],
    desc: "A compact globular cluster in Ara.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6357",
    name: "War and Peace Nebula",
    ra: 261.75,
    dec: -34.23,
    type: "Nebula",
    subType: "Emission",
    dist: "5,500 ly",
    season: ["Winter"],
    desc: "A massive star‑forming complex with intricate dust structures.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6383",
    name: "Open Cluster",
    ra: 263.65,
    dec: -32.56,
    type: "Cluster",
    subType: "Open",
    dist: "3,500 ly",
    season: ["Winter"],
    desc: "A young open cluster surrounding the massive star HD 159176.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6397",
    name: "Globular Cluster",
    ra: 265.18,
    dec: -53.67,
    type: "Cluster",
    subType: "Globular",
    dist: "7,800 ly",
    season: ["Winter"],
    desc: "One of the closest globular clusters to Earth.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6496",
    name: "Globular Cluster",
    ra: 269.77,
    dec: -44.27,
    type: "Cluster",
    subType: "Globular",
    dist: "35,000 ly",
    season: ["Winter"],
    desc: "A faint, loosely concentrated globular cluster in Scorpius.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6514",
    name: "Trifid Nebula (Duplicate)",
    ra: 270.6,
    dec: -23.0,
    type: "Nebula",
    subType: "Mixed",
    dist: "5,200 ly",
    season: ["Winter"],
    desc: "Alternate NGC designation for the Trifid Nebula.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6520",
    name: "Open Cluster",
    ra: 270.98,
    dec: -27.91,
    type: "Cluster",
    subType: "Open",
    dist: "5,500 ly",
    season: ["Winter"],
    desc: "A compact open cluster adjacent to the dark nebula Barnard 86.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6541",
    name: "Globular Cluster",
    ra: 272.01,
    dec: -43.71,
    type: "Cluster",
    subType: "Globular",
    dist: "22,800 ly",
    season: ["Winter"],
    desc: "A bright, condensed globular cluster in Corona Australis.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6584",
    name: "Globular Cluster",
    ra: 274.51,
    dec: -52.21,
    type: "Cluster",
    subType: "Globular",
    dist: "45,000 ly",
    season: ["Winter"],
    desc: "A faint globular cluster in Telescopium.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6611",
    name: "Eagle Cluster",
    ra: 274.7,
    dec: -13.8,
    type: "Cluster",
    subType: "Open",
    dist: "7,000 ly",
    season: ["Winter"],
    desc: "The open cluster powering the Eagle Nebula (M16).",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6622",
    name: "Galaxy",
    ra: 275.92,
    dec: -23.99,
    type: "Galaxy",
    subType: "Elliptical",
    dist: "80 Million ly",
    season: ["Winter"],
    desc: "A faint elliptical galaxy near the Sagittarius star clouds.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6726",
    name: "Reflection Nebula",
    ra: 284.75,
    dec: -36.98,
    type: "Nebula",
    subType: "Reflection",
    dist: "520 ly",
    season: ["Spring"],
    desc: "A bright reflection nebula in Corona Australis.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6744",
    name: "Spiral Galaxy",
    ra: 287.44,
    dec: -63.85,
    type: "Galaxy",
    subType: "Spiral",
    dist: "30 Million ly",
    season: ["Spring"],
    desc: "One of the most Milky Way‑like galaxies visible from Earth.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  
  {
    id: "NGC 6752",
    name: "Globular Cluster",
    ra: 287.71,
    dec: -59.98,
    type: "Cluster",
    subType: "Globular",
    dist: "13,000 ly",
    season: ["Spring"],
    desc: "One of the brightest and closest globular clusters, easily visible to the naked eye.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6822",
    name: "Barnard's Galaxy",
    ra: 296.24,
    dec: -14.80,
    type: "Galaxy",
    subType: "Dwarf Irregular",
    dist: "1.6 Million ly",
    season: ["Spring"],
    desc: "A nearby dwarf galaxy in the Local Group with active star‑forming regions.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6853",
    name: "Dumbbell Nebula",
    ra: 299.90,
    dec: 22.72,
    type: "Nebula",
    subType: "Planetary",
    dist: "1,360 ly",
    season: ["Spring"],
    desc: "A bright planetary nebula with a distinctive hourglass shape.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 6872",
    name: "Condor Galaxy",
    ra: 302.14,
    dec: -70.77,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "212 Million ly",
    season: ["Spring"],
    desc: "One of the largest known spiral galaxies, stretched by gravitational interaction.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7009",
    name: "Saturn Nebula",
    ra: 316.05,
    dec: -11.36,
    type: "Nebula",
    subType: "Planetary",
    dist: "5,200 ly",
    season: ["Spring"],
    desc: "A planetary nebula whose extended lobes resemble the rings of Saturn.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7099",
    name: "M30 Globular Cluster",
    ra: 325.09,
    dec: -23.18,
    type: "Cluster",
    subType: "Globular",
    dist: "27,000 ly",
    season: ["Spring"],
    desc: "A compact globular cluster with a dense core.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7293",
    name: "Helix Nebula",
    ra: 337.41,
    dec: -20.84,
    type: "Nebula",
    subType: "Planetary",
    dist: "655 ly",
    season: ["Spring"],
    desc: "One of the closest planetary nebulae to Earth, often called the Eye of God.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7424",
    name: "Spiral Galaxy",
    ra: 344.00,
    dec: -41.07,
    type: "Galaxy",
    subType: "Spiral",
    dist: "37 Million ly",
    season: ["Spring"],
    desc: "A face‑on spiral galaxy with well‑defined arms and active star formation.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7496",
    name: "Barred Spiral Galaxy",
    ra: 347.05,
    dec: -43.43,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "24 Million ly",
    season: ["Spring"],
    desc: "A barred spiral galaxy with bright star‑forming knots in its arms.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7582",
    name: "Barred Spiral Galaxy",
    ra: 349.59,
    dec: -42.37,
    type: "Galaxy",
    subType: "Barred Spiral",
    dist: "70 Million ly",
    season: ["Spring"],
    desc: "A dusty, active barred spiral galaxy in the Grus Quartet.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7590",
    name: "Spiral Galaxy",
    ra: 349.79,
    dec: -42.23,
    type: "Galaxy",
    subType: "Spiral",
    dist: "70 Million ly",
    season: ["Spring"],
    desc: "A faint spiral galaxy and member of the Grus Quartet.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7599",
    name: "Spiral Galaxy",
    ra: 350.02,
    dec: -42.25,
    type: "Galaxy",
    subType: "Spiral",
    dist: "70 Million ly",
    season: ["Spring"],
    desc: "Another member of the Grus Quartet, showing tidal distortions.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7727",
    name: "Interacting Galaxy",
    ra: 354.06,
    dec: -12.29,
    type: "Galaxy",
    subType: "Interacting",
    dist: "76 Million ly",
    season: ["Spring"],
    desc: "A post‑merger galaxy with long tidal tails and chaotic structure.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "NGC 7793",
    name: "Sculptor Group Galaxy",
    ra: 359.46,
    dec: -32.59,
    type: "Galaxy",
    subType: "Spiral",
    dist: "12.7 Million ly",
    season: ["Spring"],
    desc: "A bright spiral galaxy and member of the Sculptor Group.",
    catalog: "NGC",
    alt: null,
    az: null,
    score: null
  },
  
  // --------------------------------------------------------
  // --- PGC (Principal Galaxy Catalog) ---------------------
  // --------------------------------------------------------
  {
    id: "PGC 6240",
    name: "Irregular Galaxy",
    ra: 16.89,
    dec: -55.53,
    type: "Galaxy",
    subType: "Irregular",
    dist: "20 Million ly",
    season: ["Spring"],
    desc: "A faint irregular galaxy in the southern sky.",
    catalog: "PGC",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- SH2 (Sharpless Catalog of HII Regions) -------------
  // --------------------------------------------------------
  {
    id: "Sh2-1",
    name: "HII Region",
    ra: 6.30,
    dec: -6.00,
    type: "Nebula",
    subType: "Emission",
    dist: "1,200 ly",
    season: ["Spring"],
    desc: "A faint emission nebula in Cetus.",
    catalog: "Sh2",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Sh2-2",
    name: "HII Region",
    ra: 7.20,
    dec: -7.00,
    type: "Nebula",
    subType: "Emission",
    dist: "1,300 ly",
    season: ["Spring"],
    desc: "A diffuse HII region near the celestial equator.",
    catalog: "Sh2",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Sh2-27",
    name: "Rho Ophiuchi Shell",
    ra: 246.0,
    dec: -23.0,
    type: "Nebula",
    subType: "Emission",
    dist: "460 ly",
    season: ["Winter"],
    desc: "A large, faint emission shell surrounding the Rho Ophiuchi cloud complex.",
    catalog: "Sh2",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Sh2-54",
    name: "Eagle Nebula Complex",
    ra: 274.0,
    dec: -13.5,
    type: "Nebula",
    subType: "Emission",
    dist: "6,500 ly",
    season: ["Winter"],
    desc: "A massive HII region associated with the Eagle Nebula.",
    catalog: "Sh2",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Sh2-64",
    name: "HII Region",
    ra: 277.0,
    dec: -16.0,
    type: "Nebula",
    subType: "Emission",
    dist: "5,500 ly",
    season: ["Winter"],
    desc: "A faint emission nebula near the Omega Nebula.",
    catalog: "Sh2",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "Sh2-101",
    name: "Tulip Nebula",
    ra: 305.1,
    dec: 35.8,
    type: "Nebula",
    subType: "Emission",
    dist: "6,000 ly",
    season: ["Spring"],
    desc: "A bright emission nebula shaped like a blooming flower.",
    catalog: "Sh2",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- ESO (European Southern Observatory Catalog) --------
  // --------------------------------------------------------
  {
    id: "ESO 137-001",
    name: "Ram-Pressure Stripped Galaxy",
    ra: 242.0,
    dec: -60.6,
    type: "Galaxy",
    subType: "Spiral",
    dist: "220 Million ly",
    season: ["Winter"],
    desc: "A spiral galaxy leaving behind dramatic gas tails as it plunges through a galaxy cluster.",
    catalog: "ESO",
    alt: null,
    az: null,
    score: null
  },
  {
    id: "ESO 510-G13",
    name: "Warped Spiral Galaxy",
    ra: 197.0,
    dec: -26.0,
    type: "Galaxy",
    subType: "Spiral",
    dist: "150 Million ly",
    season: ["Autumn"],
    desc: "A heavily warped spiral galaxy likely distorted by gravitational interaction.",
    catalog: "ESO",
    alt: null,
    az: null,
    score: null
  },

  // --------------------------------------------------------
  // --- END OF DATABASE -----------------------------------
  // --------------------------------------------------------
];

// Optional default export
export default DSO_DATABASE;

// End of DSO Tracker Database
// ========================================================